import * as ImagePicker from 'expo-image-picker';
import { Image } from 'expo-image';
import { router, Stack } from 'expo-router';
import { useState } from 'react';
import { Alert, Keyboard, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { useRelationship } from '@/context/relationship-context';

export default function AddMemoryScreen() {
  const [photoUri, setPhotoUri] = useState<string>();
  const [caption, setCaption] = useState('');
  const { addMemory, relationshipName } = useRelationship();
  const choosePhoto = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { Alert.alert('Photo access needed', 'Allow photo access to save a photo memory.'); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [4, 3], quality: 0.8 }); if (!result.canceled) setPhotoUri(result.assets[0].uri); };
  const save = () => { if (!photoUri) { Alert.alert('Choose a photo', 'A photo is required for a new moment.'); return; } const note = caption.trim(); Keyboard.dismiss(); addMemory({ title: note ? note.slice(0, 56) : 'A photo memory', body: note || `A photo saved in ${relationshipName || 'this relationship'}.`, photoUri }); router.replace('/relationship-timeline'); };
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} contentInsetAdjustmentBehavior="automatic" keyboardDismissMode="interactive" keyboardShouldPersistTaps="handled"><Stack.Screen options={{ title: 'Add a photo moment' }} /><Text selectable style={styles.title}>Save a photo</Text><Text selectable style={styles.copy}>Photos become private moments in {relationshipName || 'this relationship'}.</Text><Pressable accessibilityRole="button" onPress={choosePhoto} style={styles.photoArea}>{photoUri ? <Image source={{ uri: photoUri }} contentFit="cover" style={styles.preview} /> : <><Text style={styles.plus}>+</Text><Text style={styles.pick}>Choose a photo</Text><Text style={styles.hint}>Only photos can be added here</Text></>}</Pressable><View style={styles.captionCard}><Text selectable style={styles.captionLabel}>ADD A CAPTION</Text><TextInput value={caption} onChangeText={setCaption} multiline placeholder="What would you like to remember about this moment?" placeholderTextColor="#A89184" textAlignVertical="top" style={styles.captionInput} /></View><Pressable accessibilityRole="button" onPress={save} style={[styles.save, !photoUri && styles.saveDisabled]}><Text style={styles.saveText}>Post photo moment</Text></Pressable></ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#FBF7F1'},content:{padding:20,paddingBottom:40,gap:16},title:{color:'#493B33',fontSize:27,fontWeight:'700'},copy:{color:'#806F65',fontSize:15,lineHeight:21},photoArea:{height:290,overflow:'hidden',alignItems:'center',justifyContent:'center',gap:7,borderRadius:24,backgroundColor:'#E7E3D1'},preview:{width:'100%',height:'100%'},plus:{fontSize:42,color:'#8C7E49'},pick:{color:'#554F3E',fontSize:16,fontWeight:'700'},hint:{color:'#817A67',fontSize:12},captionCard:{minHeight:124,padding:15,gap:7,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:'#F0E8E0'},captionLabel:{color:'#A17460',fontSize:10,fontWeight:'800',letterSpacing:.9},captionInput:{flex:1,minHeight:70,color:'#493B33',fontSize:16,lineHeight:22,padding:0},save:{padding:16,borderRadius:16,backgroundColor:'#C9826A'},saveDisabled:{backgroundColor:'#D6B2A5'},saveText:{color:'#FFFFFF',fontSize:15,fontWeight:'800',textAlign:'center'}});
