import { router, Stack } from 'expo-router';
import { useMemo } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Image } from 'expo-image';
import { CheckIn, Memory, useRelationship } from '@/context/relationship-context';

const DAY_IN_MS = 86400000;

function getAiSummary(checkIn?: CheckIn) {
  if (!checkIn) return 'No check-ins yet. A small update can help you stay close.';
  if (checkIn.mood === 'Not feeling well') return `${checkIn.person} has had a difficult day and may appreciate a quiet, supportive evening.`;
  if (checkIn.mood === 'Great') return `${checkIn.person} is feeling positive and grateful today. It is a good moment to celebrate the little things together.`;
  if (checkIn.mood === 'Missing you') return `${checkIn.person} is holding a tender memory close today and may find comfort in sharing a story.`;
  return `${checkIn.person} is taking today one step at a time and has shared a gentle update.`;
}

function fallbackCheckIn(person: string) {
  const defaults: Record<string, Pick<CheckIn, 'mood' | 'emoji' | 'note'>> = {
    Joyce: { mood: 'Great', emoji: '😊', note: 'Feeling grateful for our little routines today.' }, Brian: { mood: 'Okay', emoji: '🙂', note: 'Looking forward to a quiet evening together.' }, James: { mood: 'Great', emoji: '😊', note: 'Feeling happy to see the family doing well.' }, Sarah: { mood: 'Great', emoji: '😊', note: 'Sending love and thinking of everyone today.' }, Grandma: { mood: 'RIP', emoji: '🕊', note: 'Her warmth is close in our hearts today.' }, Grandpa: { mood: 'RIP', emoji: '🕊', note: 'His stories stay with us.' },
  };
  return { id: `seeded-${person}`, person, ...(defaults[person] ?? { mood: 'Okay', emoji: '🙂', note: 'Holding this relationship close today.' }), createdAt: '' };
}

export default function HomeScreen() {
  const { relationshipName, startDate, reminderYears, activeRelationship } = useRelationship();
  const memories = activeRelationship.memories;
  const checkIns = [...activeRelationship.checkIns].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  const memberAliases: Record<string, string> = { 'Mommy (Joyce)': 'Joyce', 'Daddy (Brian)': 'Brian', 'Dad (James)': 'James', 'Mom (Sarah)': 'Sarah' };
  const memberNames = activeRelationship.members.split(/,|&/).map((name) => name.trim()).filter((name) => name && name !== 'Baby Mila');
  const peopleCheckIns = [...memberNames.map((person) => { const checkIn = checkIns.find((entry) => entry.person === (memberAliases[person] ?? person)); const latest = checkIn ?? fallbackCheckIn(person); return { ...latest, person, isMemorial: latest.mood === 'RIP' }; }), ...(activeRelationship.memorialMembers ?? []).map((person) => ({ id: `memorial-${person}`, person, mood: 'RIP', emoji: '🕊', note: 'Remembered with love.', createdAt: '', isMemorial: true }))];
  const latestMemory = [...memories].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())[0];
  const nextEvent = [...activeRelationship.futureEvents].sort((a, b) => a.date.localeCompare(b.date))[0];
  const daysTogether = useMemo(() => { const parsed = new Date(`${startDate}T00:00:00`); return Number.isNaN(parsed.getTime()) ? null : Math.max(0, Math.floor((Date.now() - parsed.getTime()) / DAY_IN_MS)); }, [startDate]);
  const eventDays = nextEvent ? Math.max(0, Math.ceil((new Date(`${nextEvent.date}T00:00:00`).getTime() - Date.now()) / DAY_IN_MS)) : null;
  const flashbacks = reminderYears.map((yearsAgo) => ({ yearsAgo, memory: memories.filter((memory) => new Date(memory.createdAt).getFullYear() === new Date().getFullYear() - yearsAgo).sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())[0] }));
  return <><Stack.Screen options={{ headerShown: false }} /><ScrollView style={s.screen} contentContainerStyle={s.content} contentInsetAdjustmentBehavior="automatic"><View style={s.top}><Pressable onPress={() => router.push('/relationships')} style={s.round}><Text style={s.menu}>☰</Text></Pressable><Pressable onPress={() => router.push('/profile')} style={s.profile}><Text style={s.profileIcon}>👤</Text></Pressable></View><View><Text style={s.name}>{relationshipName || 'New relationship'}</Text><Text style={s.sub}>{daysTogether === null ? 'Add a relationship start date' : `${daysTogether.toLocaleString()} days together`}</Text></View><View style={s.checkCard}><View style={s.heading}><Text style={s.eyebrow}>MOST RECENT CHECK-IN</Text><Text style={s.section}>A little pulse, together</Text></View><View style={s.aiHighlight}><Text style={s.eyebrow}>TODAY'S HIGHLIGHT</Text><Text style={s.aiText}>{getAiSummary(checkIns[0])}</Text></View><View style={s.latestPeople}>{peopleCheckIns.map((entry) => <Pressable key={entry.id} disabled={entry.isMemorial} onPress={() => router.push({ pathname: '/check-in-detail', params: { person: entry.person } })} style={[s.conditionChip, entry.isMemorial && s.memorialChip]}><Text style={[s.conditionEmoji, entry.isMemorial && s.memorialText]}>{entry.emoji}</Text><View><Text style={[s.conditionName, entry.isMemorial && s.memorialText]}>{entry.person}</Text><Text style={[s.conditionMood, entry.isMemorial && s.memorialText]}>{entry.mood}</Text></View></Pressable>)}</View></View>{nextEvent && <Pressable onPress={() => router.push('/future-events')} style={s.event}><Text style={s.eventDays}>{eventDays}</Text><View style={s.eventCopy}><Text style={s.eventTitle}>days until {nextEvent.title}</Text><Text style={s.eventNote}>{nextEvent.note}</Text></View></Pressable>}<View style={s.heading}><Text style={s.eyebrow}>YOUR LATEST CHAPTER</Text><Text style={s.section}>Our last memory</Text></View><MemoryCard memory={latestMemory} /><View style={s.heading}><Text style={s.eyebrow}>A LITTLE THROWBACK</Text><Text style={s.section}>From this day</Text></View><View style={s.flashbackList}>{flashbacks.map(({ yearsAgo, memory }) => <Pressable key={yearsAgo} onPress={() => router.push('/relationship-timeline')} style={s.flashbackCard}><Text style={s.flashbackYear}>{yearsAgo} {yearsAgo === 1 ? 'YEAR' : 'YEARS'} AGO</Text><Text style={s.flashbackTitle}>{memory?.title || 'No memory saved yet'}</Text><Text style={s.flashbackNote}>{memory?.body || `Save a memory from ${new Date().getFullYear() - yearsAgo} to revisit it here.`}</Text></Pressable>)}</View></ScrollView></>;
}

function MemoryCard({ memory }: { memory?: Memory }) { return <Pressable onPress={() => router.push('/relationship-timeline')} style={s.memory}>{memory?.photoUri ? <Image source={{ uri: memory.photoUri }} contentFit="cover" style={s.photo} /> : <View style={s.cover}><Text style={s.coverEmoji}>{memory?.coverEmoji || '+'}</Text></View>}<View style={s.memoryCopy}><Text style={s.memoryDate}>{memory ? new Date(memory.createdAt).toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' }) : 'A PLACE TO BEGIN'}</Text><Text style={s.memoryTitle}>{memory?.title || 'Save your first memory'}</Text><Text style={s.memoryNote}>{memory?.body || 'Photos and memories saved here belong to this relationship only.'}</Text></View></Pressable>; }

const s = StyleSheet.create({ screen:{flex:1,backgroundColor:'#FBF7F1'},content:{paddingHorizontal:20,paddingTop:16,paddingBottom:128,gap:22},top:{flexDirection:'row',justifyContent:'space-between'},round:{width:42,height:42,borderRadius:21,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},profile:{width:42,height:42,borderRadius:21,backgroundColor:'#E8D2C4',alignItems:'center',justifyContent:'center'},profileIcon:{fontSize:20},menu:{color:'#876F63',fontSize:20},name:{color:'#47382F',fontSize:32,fontWeight:'700',letterSpacing:-1},sub:{color:'#9A7869',fontSize:14,fontWeight:'600',marginTop:5},checkCard:{padding:16,gap:13,borderRadius:24,backgroundColor:'#fff',borderWidth:1,borderColor:'#F0E8E0'},heading:{gap:4},eyebrow:{color:'#A17460',fontSize:10,fontWeight:'800',letterSpacing:1},section:{color:'#493B33',fontSize:25,fontWeight:'700'},aiHighlight:{padding:16,gap:6,borderRadius:19,backgroundColor:'#E7E3D1'},aiText:{color:'#5D594A',fontSize:15,lineHeight:21},latestPeople:{gap:9,padding:10,borderRadius:16,backgroundColor:'#F8F4EF'},conditionChip:{width:'100%',flexDirection:'row',alignItems:'center',gap:9,padding:10,borderRadius:12,backgroundColor:'#fff'},conditionEmoji:{color:'#705548',fontSize:20},conditionName:{color:'#493B33',fontSize:13,fontWeight:'800'},conditionMood:{color:'#806F65',fontSize:10,marginTop:1},memorialChip:{backgroundColor:'#F4F4F5'},memorialText:{color:'#8E8E93'},event:{flexDirection:'row',alignItems:'center',gap:12,padding:15,borderRadius:20,backgroundColor:'#F1E5DC'},eventDays:{color:'#A26351',fontSize:28,fontWeight:'800',flexShrink:0},eventCopy:{flex:1},eventTitle:{color:'#554238',fontSize:15,fontWeight:'800'},eventNote:{color:'#8D7468',fontSize:12,marginTop:3},memory:{overflow:'hidden',borderRadius:24,backgroundColor:'#fff',borderWidth:1,borderColor:'#F0E8E0'},cover:{height:184,alignItems:'center',justifyContent:'center',backgroundColor:'#D7B99A'},coverEmoji:{fontSize:68},photo:{height:184,width:'100%'},memoryCopy:{padding:17,gap:5},memoryDate:{color:'#A0715C',fontSize:10,fontWeight:'800',letterSpacing:.9},memoryTitle:{color:'#47382F',fontSize:21,fontWeight:'700'},memoryNote:{color:'#806F65',fontSize:14,lineHeight:20},flashbackList:{gap:10},flashbackCard:{padding:19,gap:6,borderRadius:24,backgroundColor:'#E7E3D1'},flashbackYear:{color:'#887C48',fontSize:10,fontWeight:'800',letterSpacing:1},flashbackTitle:{color:'#4D4A39',fontSize:21,fontWeight:'700'},flashbackNote:{color:'#6B6756',fontSize:14,lineHeight:20} });
