import { router, Stack, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { DateInput } from '@/components/date-input';
import { useRelationship } from '@/context/relationship-context';

const emails:Record<string,string>={Joyce:'joyce@example.com',Brian:'brian@email.com',James:'james@email.com',Sarah:'sarah@email.com','Baby Mila':'mila@ourfamily.com',Grandma:'grandma@family.com',Grandpa:'grandpa@family.com'};
const colors=['#E8D2C4','#D6DDC2','#D6D0E6','#F1E5DC'];

export default function RelationshipSettingsScreen(){const params=useLocalSearchParams<{create?:string;name?:string;members?:string;startDate?:string}>();const creating=params.create==='1';const current=useRelationship();const [draftName,setDraftName]=useState(params.name??'');const [draftStartDate,setDraftStartDate]=useState(params.startDate??new Date().toISOString().slice(0,10));const name=creating?draftName:current.relationshipName;const members=creating?(params.members??''):current.members;const startDate=creating?draftStartDate:current.startDate;const people=members.split(/,|&/).map((item)=>item.trim()).filter(Boolean);const save=()=>{if(!draftName.trim()){Alert.alert('Give this relationship a name','Add a name before saving.');return;}current.addRelationship({name:draftName.trim(),members,startDate});router.replace('/');};const openMembers=()=>router.push({pathname:'/select-members',params:{name:draftName,startDate,draftMembers:members}});return <><Stack.Screen options={{title:creating?'Create a relationship':'Relationship settings'}}/><ScrollView style={s.screen} contentContainerStyle={s.content} contentInsetAdjustmentBehavior="automatic" keyboardDismissMode="interactive" keyboardShouldPersistTaps="handled">{creating?<Text selectable style={s.intro}>Create a private space for the people and memories that matter.</Text>:<Text selectable style={s.intro}>Shape this space around the relationship you share.</Text>}<View style={s.card}><Text selectable style={s.label}>RELATIONSHIP NAME</Text><TextInput value={name} onChangeText={creating?setDraftName:current.setRelationshipName} placeholder="Give this relationship a name" placeholderTextColor="#A89184" style={s.input}/><View style={s.divider}/><Text selectable style={s.label}>START DATE</Text><DateInput value={startDate} onChange={creating?setDraftStartDate:current.setStartDate}/></View><View style={s.membersHeading}><Text selectable style={s.label}>MEMBERS</Text><Text selectable style={s.membersHelper}>People who share this relationship space</Text></View>{people.length?<View style={s.memberList}>{people.map((person,index)=><View key={person} style={s.memberCard}><View style={[s.avatar,{backgroundColor:colors[index%colors.length]}]}><Text style={s.avatarText}>{person.charAt(0).toUpperCase()}</Text></View><View><Text selectable style={s.memberName}>{person}</Text><Text selectable style={s.memberEmail}>{emails[person]??`${person.toLowerCase().replace(/\s+/g,'.')}@email.com`}</Text></View></View>)}</View>:<Pressable onPress={openMembers} style={s.addPeopleCard}><Text style={s.addPeopleText}>+ Add people to this space</Text></Pressable>}{creating&&people.length>0&&<Pressable onPress={openMembers} style={s.changePeople}><Text style={s.changePeopleText}>Edit people</Text></Pressable>}{creating&&<Pressable onPress={save} style={s.save}><Text style={s.saveText}>Save this relationship</Text></Pressable>}</ScrollView></>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#FBF7F1'},content:{padding:20,paddingBottom:80,gap:18},intro:{color:'#806F65',fontSize:16,lineHeight:22},card:{padding:17,gap:7,borderRadius:21,backgroundColor:'#fff',borderWidth:1,borderColor:'#F0E8E0'},label:{color:'#A17460',fontSize:10,fontWeight:'800',letterSpacing:.95},input:{color:'#493B33',fontSize:17,fontWeight:'700',paddingVertical:4},divider:{height:1,backgroundColor:'#F0E8E0',marginVertical:8},membersHeading:{gap:4},membersHelper:{color:'#88766B',fontSize:14},memberList:{gap:10},memberCard:{flexDirection:'row',alignItems:'center',gap:13,padding:14,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:'#F0E8E0'},avatar:{width:46,height:46,borderRadius:23,alignItems:'center',justifyContent:'center'},avatarText:{color:'#5E4D45',fontSize:17,fontWeight:'800'},memberName:{color:'#493B33',fontSize:16,fontWeight:'800'},memberEmail:{color:'#806F65',fontSize:13,marginTop:3},addPeopleCard:{padding:17,borderRadius:20,backgroundColor:'#F0E5DC'},addPeopleText:{color:'#875F50',fontWeight:'800'},changePeople:{alignSelf:'flex-start',paddingHorizontal:12,paddingVertical:8,borderRadius:12,backgroundColor:'#F0E5DC'},changePeopleText:{color:'#875F50',fontSize:13,fontWeight:'800'},save:{alignItems:'center',padding:16,borderRadius:16,backgroundColor:'#C9826A'},saveText:{color:'#fff',fontSize:15,fontWeight:'800'}});
