import { router, Stack, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { DateInput } from '@/components/date-input';
import { useRelationship } from '@/context/relationship-context';

const emails:Record<string,string>={Joyce:'joyce@example.com',Brian:'brian@email.com',Sarah:'sarah@email.com',James:'james@email.com',Grandma:'grandma@family.com',Grandpa:'grandpa@family.com'};
export default function Settings(){const p=useLocalSearchParams<{create?:string;name?:string;members?:string;startDate?:string;memorialMembers?:string}>();const creating=p.create==='1';const r=useRelationship();const [name,setName]=useState(p.name??'');const [date,setDate]=useState(p.startDate??new Date().toISOString().slice(0,10));const members=creating?(p.members??''):r.members;const people=members.split(/,|&/).map(x=>x.trim()).filter(Boolean);const memorialMembers=(creating?(p.memorialMembers??''):(r.activeRelationship.memorialMembers??[]).join(', ')).split(',').map(x=>x.trim()).filter(Boolean);const choose=()=>router.push({pathname:'/select-members',params:{name, startDate:date,draftMembers:members}});const addMemorial=()=>router.push({pathname:'/add-memorial-members',params:{name,startDate:date,members,memorialMembers:memorialMembers.join(', ')}});const save=()=>{if(!name.trim())return Alert.alert('Give this relationship a name');r.addRelationship({name:name.trim(),members,memorialMembers,startDate:date});router.replace('/')};return <><Stack.Screen options={{title:creating?'Create a relationship':'Relationship settings'}}/><ScrollView style={s.screen} contentContainerStyle={s.content} contentInsetAdjustmentBehavior="automatic"><Text style={s.intro}>{creating?'Create a private space for the people and memories that matter.':'Shape this space around the relationship you share.'}</Text><View style={s.card}><Text style={s.label}>RELATIONSHIP NAME</Text><TextInput value={creating?name:r.relationshipName} onChangeText={creating?setName:r.setRelationshipName} placeholder="Give this relationship a name" placeholderTextColor="#A89184" style={s.input}/><View style={s.line}/><Text style={s.label}>START DATE</Text><DateInput value={creating?date:r.startDate} onChange={creating?setDate:r.setStartDate}/></View><Text style={s.label}>MEMBERS</Text>{people.map((person)=><View key={person} style={s.person}><Text style={s.avatar}>{person[0]}</Text><View><Text style={s.personName}>{person}</Text><Text style={s.email}>{emails[person]??`${person.toLowerCase().replace(/\s+/g,'.')}@email.com`}</Text></View></View>)}{memorialMembers.map((person)=><View key={`memorial-${person}`} style={s.memorialPerson}><Text style={s.memorialAvatar}>🕊</Text><View><Text style={s.memorialName}>{person}</Text><Text style={s.memorialStatus}>RIP</Text></View></View>)}{creating&&<><Pressable onPress={choose} style={s.add}><Text style={s.addText}>+ Add people to this space</Text></Pressable><Pressable onPress={addMemorial} style={s.add}><Text style={s.addText}>+ Add people here if they have passed away</Text></Pressable><Pressable onPress={save} style={s.save}><Text style={s.saveText}>Save this relationship</Text></Pressable></>}</ScrollView></>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#FBF7F1'},content:{padding:20,gap:14,paddingBottom:80},intro:{color:'#806F65',fontSize:16,lineHeight:22},card:{padding:17,gap:7,borderRadius:21,backgroundColor:'#fff',borderWidth:1,borderColor:'#F0E8E0'},label:{color:'#A17460',fontSize:10,fontWeight:'800',letterSpacing:1},input:{color:'#493B33',fontSize:17,fontWeight:'700',paddingVertical:4},line:{height:1,backgroundColor:'#F0E8E0',marginVertical:8},person:{flexDirection:'row',alignItems:'center',gap:12,padding:13,borderRadius:18,backgroundColor:'#fff',borderWidth:1,borderColor:'#F0E8E0'},avatar:{width:42,height:42,lineHeight:42,borderRadius:21,textAlign:'center',textAlignVertical:'center',includeFontPadding:false,transform:[{translateY:-2}],backgroundColor:'#E8D2C4',color:'#705548',fontWeight:'800'},personName:{color:'#493B33',fontSize:16,fontWeight:'800'},email:{color:'#806F65',fontSize:13,marginTop:2},memorialPerson:{flexDirection:'row',alignItems:'center',gap:12,padding:13,borderRadius:18,backgroundColor:'#F5F5F6',borderWidth:1,borderColor:'#E5E5E8'},memorialAvatar:{width:42,height:42,lineHeight:42,borderRadius:21,textAlign:'center',textAlignVertical:'center',includeFontPadding:false,transform:[{translateY:-2}],backgroundColor:'#E2E2E5',fontSize:19},memorialName:{color:'#8E8E93',fontSize:16,fontWeight:'800'},memorialStatus:{color:'#8E8E93',fontSize:13,marginTop:2},add:{padding:16,borderRadius:18,backgroundColor:'#F0E5DC'},addText:{color:'#875F50',fontWeight:'800'},save:{padding:16,borderRadius:16,backgroundColor:'#C9826A'},saveText:{color:'#fff',fontWeight:'800',textAlign:'center'}});
